relative positions
decentraland-scenes/dcl-ui-toolkit pull request #6
Opened 2024-07-22 20:35 UTC by nearnshaw

2024-07-22 21:51 UTC, AlejandroAlvarezMelucciDCL requested changes
Looks good overall but I'd like you to double check some comments, I might be wrong and no action is needed, let me know and I'll change the approval 😄

2024-07-22 21:51 UTC, AlejandroAlvarezMelucciDCL commented on README.md
> +const optionPrompt = ui.createComponent(ui.OptionPrompt, {
I think we should also rename `prompt` in line 635:
`prompt.show()` to `optionPrompt.show()`

2024-07-22 21:51 UTC, AlejandroAlvarezMelucciDCL commented on src/ui-entities/prompts/Prompt/components/Switch/index.tsx
>          }}
Is the double `{{` and `}}` intended?

2024-07-22 21:51 UTC, AlejandroAlvarezMelucciDCL commented on src/ui-entities/prompts/Prompt/components/Icon/index.tsx
> +        positionType: this.absolute,
You changed `positionType` to use a string elsewhere but here `this.absolute` is a boolean, I think that might cause unexpected behavior, can you check?

2024-07-22 21:51 UTC, AlejandroAlvarezMelucciDCL commented on src/ui-entities/prompts/Prompt/index.tsx
> +              // },
Maybe we can delete commented out code? As well as in line 243

2024-07-23 13:12 UTC, nearnshaw commented on README.md
> +const optionPrompt = ui.createComponent(ui.OptionPrompt, {
Yep, this is from making examples copying and pasting the same code XD

2024-07-23 13:14 UTC, nearnshaw commented on src/ui-entities/prompts/Prompt/components/Switch/index.tsx
>          }}
It is intended
It's a bit weird if you ask me, but that's how our UIs are written for some reason
https://docs.decentraland.org/creator/development-guide/sdk7/onscreen-ui/

2024-07-23 13:15 UTC, nearnshaw commented on src/ui-entities/prompts/Prompt/components/Icon/index.tsx
> +        positionType: this.absolute,
thx, good point, this property doesn't know what to do with a boolean
I just replaced it with
this.absolute ? 'absolute' : 'relative',

2024-07-23 13:17 UTC, nearnshaw commented on src/ui-entities/prompts/Prompt/index.tsx
> +              // },
yes, for sure
I was just leaving this in for now while I tried things semi randomly without knowing if I have to uncomment them :p

2024-07-23 13:51 UTC, AlejandroAlvarezMelucciDCL approved these changes
LGTM!

2024-12-02 20:24 UTC, merged